# Generated by Django 2.0.4 on 2018-06-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180619_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='courses_nums',
            new_name='course_nums',
        ),
    ]
